### ISSUE TITLE
Remove Termennetwerk from demo page

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/demo-frontend#15]
The entry for the netwerk-of-terms on the demo page should be removed as we decided it has no longer the demo status and the front-end is available now through a dedicated url.

**Comment by ddeboer** [comment]
Good one!

Does it still make sense to have some overview of Bruikbaar apps (e.g. `https://apps.netwerkdigitaalerfgoed.nl`)? Or can we just use the main site `https://netwerkdigitaalerfgoed.nl/bruikbaar/` for that?

(We have https://github.com/netwerk-digitaal-erfgoed/bruikbaar#repositories, but that one is private on purpose.)

**Comment by EnnoMeijers** [comment]
I think a general overview of all the Bruikbaar apps (with a few lines of documentation) would be a good idea. My preference is to do this on https://apps.netwerkdigitaalerfgoed.nl and maybe replicate some of them on the NDE website or even just make a pointer over there to the apps sites.
